---
title: "Memory recall analysis"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
respData=read.table('https://raw.githubusercontent.com/psych10/psych10/master/exercises/memoryRecall/Memory%20recall%20test.csv',header=TRUE,sep=',',
             stringsAsFactors = FALSE)
```

```{r}
respData$nRecalled=NULL
respData$nHits=0

# last item in this list is the DRM critical lure

listWords=c('fear','temper','hatred','fury','happy',
            'enrage','emotion','rage','hate','mean',
            'ire','mad','wrath','fight','anger')

itemData=c()

for (i in 1:dim(respData)[1]){
  split_resp=strsplit(tolower(respData[i,2]),' ')[[1]]
  respData$nRecalled[i]=length(split_resp)
  
  for (j in 1:length(listWords)){
    itemData=rbind(itemData,c(j,as.integer(listWords[j] %in% split_resp)))
  }
}
itemDataDf=as.data.frame(itemData)
names(itemDataDf)=c('position','hit')
```

Plot serial position curve

```{r}
source('summarySE.R')
sm=summarySE(itemDataDf, 
             measurevar="hit", groupvars=c("position"))

itemDataDf <- itemDataDf %>%
  mutate(lure = as.integer(position==length(listWords)))

lureHitRate = mean(itemDataDf$hit[itemDataDf$lure==TRUE])


ggplot(subset(sm,position<length(listWords)),aes(x=position,y=hit)) +
  geom_line() + 
  geom_hline(yintercept=lureHitRate,color='blue') + 
  ylim(0,1) + ylab('Proportion correct recall') + 
  xlab('Serial position of item in list') +
  annotate('text',label = "hit rate for lure ('anger')", x = 7, y = lureHitRate*0.85, colour = "blue") + 
  scale_x_continuous(breaks=1:(length(listWords)-1),
                   labels=listWords[1:(length(listWords)-1)]) +
  theme(axis.text.x  = element_text(angle=90, size=12,vjust=0.5))

```



